language: go

go:
  - 1.6

install:
  - go get -v -u golang.org/x/lint/golint
  - go get -v
  - go build -v ./...

script:
  - go test ./...
  - test -z "$(go fmt ./...)"
  - test -z "$(golint .)"
  - go vet
